### ISSUE TITLE
Branching Ratio Error

### ISSUE THREAD

**Issue by AdrianaUreche** [fzeiser/RAINIER#14]
Branching ratio error appears for transitions from a ConBin to a DiscLvl where the branching ratio does not equal one. Error message also indicates a reference a ConBin beginning at -1 and to a negative value of levels in ConBin. The error does not seem to refer to the branching ratios of the discrete states. Below is the error message

Example:
```
err: JP: from 
5-, Lvl: 15, ConBin: -1;59
To 
-7+, Lvl: 15, ConBin: -1;-7
Likely branching ratios from file don't add to 1.000000
Check level 15 in zFile manually.  
```

In RAINIER:
```
if(nToSpb < 0 || nToPar < 0 || nToLvlInBin < 0 ) { // error check
    cerr << endl << "err: JP: from " << endl 
         << nSpb << (nPar?"+":"-") << ", Lvl: " << nDisEx << ", ConBin: " 
         << nConEx << ";" << nLvlInBin << endl << "To " << endl
         << nToSpb << (nToPar?"+":"-") << ", Lvl: " << nToDisEx << ", ConBin: "
         << nToConEx << ";" << nToLvlInBin << endl 
         << "Likely branching ratios from file don't add to 1.000000" << endl 
         << "Check level " << nDisEx << " in " << "zFile" << " manually." 
         << endl;
         // else write code to normalize
    return false;
  } // err
```

**Comment by fzeiser** [comment]
I wonder whether you checked the following: Could it be that you try to populate levels that don't exist? I had something similar yesterday, but it was fixed when I populated the correct discrete states.

The `ConBin: -1` means that it's a discrete state. Would you mind to attach your `settings.h` file?

**Comment by hannahberg** [comment]
When populating a single level at 7 MeV I also get a branching ratio error:

`err: JP: from 
0-, Lvl: 2, ConBin: -1;0
To 
-7+, Lvl: 6, ConBin: -1;-7
Likely branching ratios from file don't add to 1.000000
Check level 2 in zFile manually.
`
This is for Ni-71.

**Comment by fzeiser** [comment]
@hannahberg: What a nice and funny way to hear from you.

Can you attach a complete example, i.e. settings file and RAINIER commit?

**Comment by fzeiser** [comment]
I think it usually also helps printing the output of `PrintDisLvl()` before one might dig deeper into the levels file.

**Comment by hannahberg** [comment]
@fzeiser Thanks for answering so quickly, it is nice to meet over github!
I am using the latest release (884280d).
[settings.zip](https://github.com/fzeiser/RAINIER/files/5037826/settings.zip)

**Comment by fzeiser** [comment]
The error message is correct, your 2nd level doesn't have a branching ratio in the file, see also [NNDC](https://www.nndc.bnl.gov/chart/getdataset.jsp?nucleus=71Ni&unc=nds). Thus RAINIER gives a warning/error when you try to de-excite the nucleus and run through this level.

**Comment by fzeiser** [comment]
It's now up to your own what you want to do - you might make a good assumption about how the nucleus decays from the 2nd state to either 1st or gs. and put this into the levels file. You might want to use a *magic* levels file for it, the `mylevels_zXXX` placed in the same folder as the settings file. It will overwrite the levels file in `levels`, but you don't need to edit the source code.

**Comment by fzeiser** [comment]
Please feel free to ask if you have further questions, otherwise please close the issue.

**Comment by hannahberg** [comment]
Thank you @fzeiser 
Since I only commented here, I think @AdrianaUreche might need to close the issue.

**Comment by fzeiser** [comment]
I'll close the issue for now due to inactivity. It seems like my suggestion from Oct 2, 2018 hinted towards the same problem.

**Comment by fzeiser** [comment]
See also #20, it's the same issue
