### ISSUE TITLE
briccsMac not running

### ISSUE THREAD

**Issue by aspyrou** [fzeiser/RAINIER#19]
Hello, 
A few months ago I upgraded my MAC to the new OS Catalina which uses zsh instead of bash. I've had to reinstall a lot of things and make them work. I just tried to run RAINIER and it runs ok but I get an error for briccsMac
"zsh: bad CPU type in executable: briccsMac"

Any suggestions?
Thanks
Artemis

**Comment by fzeiser** [comment]
Did you test the 64 bit version of briccs as recommended (and uploaded ) in #18 ?

**Comment by fzeiser** [comment]
Hm, wait a second: I guess you need to have different compiler settings for mac. Anyhow, you might ask Tibor to compile Briccs for mac; 64 bit

**Comment by aspyrou** [comment]
ok, thanks I'll try 
BTW I'm also getting another error that you might be able to help with:
err: JP: from 
2+, Lvl: 7, ConBin: -1;0
To 
-7+, Lvl: 10, ConBin: -1;-7
Likely branching ratios from file don't add to 1.000000
Check level 7 in zFile manually.

err: JP: from 
2-, Lvl: 9, ConBin: -1;0
To 
-7+, Lvl: 10, ConBin: -1;-7
Likely branching ratios from file don't add to 1.000000
Check level 9 in zFile manually.

Branchings seem to add to 1.0 so I'm not sure what the issue is

Thanks
Artemis

**Comment by aspyrou** [comment]
So the briccs zip file from #18 did not work either (different error)
zsh: exec format error: ./briccs

**Comment by fzeiser** [comment]
As mentioned above, the file uploaded in #18 is compiled for linux.

**Comment by fzeiser** [comment]
@aspyrou Does it work with the new executable?

**Comment by aspyrou** [comment]
Yes it does. Thanks for the help
