### ISSUE TITLE
Likely branching ratios from file don't add to 1.000000

### ISSUE THREAD

**Issue by fzeiser** [fzeiser/RAINIER#20]
From Artemis:

BTW I'm also getting another error that you might be able to help with:

> err: JP: from 
> 2+, Lvl: 7, ConBin: -1;0
> To 
> -7+, Lvl: 10, ConBin: -1;-7
> Likely branching ratios from file don't add to 1.000000
> Check level 7 in zFile manually.
> 
> err: JP: from 
> 2-, Lvl: 9, ConBin: -1;0
> To 
> -7+, Lvl: 10, ConBin: -1;-7
> Likely branching ratios from file don't add to 1.000000
> Check level 9 in zFile manually.

Branchings seem to add to 1.0 so I'm not sure what the issue is

Thanks
Artemis

_Originally posted by @aspyrou in https://github.com/fzeiser/RAINIER/issues/19#issuecomment-638840781_

**Comment by fzeiser** [comment]
Could you post more information on this? I need the settings file to check this [eg what nucleus you look at]

**Comment by aspyrou** [comment]
This is 76Ge and I'm using the version you sent to me a few months ago for the shape method

**Comment by fzeiser** [comment]
Can you run `git log` and paste the lasted commit id?

**Comment by fzeiser** [comment]
- How did you verify that the branchings seem to add to 1.0? 
- Could you paste the output of `PrintDisLvl()`
- If I look at the levels file, I immediately see another problem: the levels don't have a reported halflife

**Comment by aspyrou** [comment]
I'm not getting anything from git log. You had sent me a zip file. Do you want me to send you the RAINIER-shape.zip file back or do you still have it?

**Comment by fzeiser** [comment]
> I'm not getting anything from git log. You had sent me a zip file. Do you want me to send you the RAINIER-shape.zip file back or do you still have it?

No; it seems to me like the problem is anyhow more related to the levels file, and they were not changed. But the error message might have changed.
To make sure you know what version you operate with then, just paste the settings file(s)  / necessary files in a new folder and run it with a RAINIER version of you choice.

**Comment by AdrianaUreche** [comment]
I've checked the 76Ge and I see that there are a few levels without gamma rays, e.g. level #10 has 0 gammas.  This as well as the half-lives reported in the file may be the root of the error message.  You could change the number of discrete levels you include in the run to only 9 and see if you still gives you the error message?

**Comment by aspyrou** [comment]
Thanks for checking Adriana. 9 levels is still a problem. Only 6 or less is ok. there is something wrong with level 7 that I can't figure out.

**Comment by fzeiser** [comment]
Did you check the halflives as I asked for above? And the PrinDisLvl()

Because the halflives are not reported, the rest of the line will not be read correctly either?

**Comment by fzeiser** [comment]
I found out that I had some simulations for 76Ge.
- With a5d4690fccd35f5934f4a2247af63a9a8dc15c30, I get a descriptive error message on which levels don't have a reported halflive. These need to be handled somehow. I provided the optional `mylevels_z032.dat` file.

`PrinDisLvl()` Without modification:
```
****** Discrete ******
i 	 E 	 J 	 Pi(1=+) 	 T1/2
	 i_final 	 Br
 ---------------------- 
0:	 0   0+ N/A
1:	 0.56293   2+ 18200 fs
   0 : 1
2:	 1.10844   2+ 8000 fs
   1 : 0.5956
   0 : 0.4044
3:	 1.41008   4+ 1800 fs
   1 : 1
4:	 1.53946   3+ N/A
   2 : 0.6672
   1 : 0.3328
5:	 1.91107   0+ 800 fs
   1 : 1
6:	 2.01987   4+ N/A
   2 : 1
7:	 2.2049   2+ 10 fs
   2 : -nan
   0 : -nan
```

with the modified level scheme:
```
root [1] PrintDisLvl()
****** Discrete ******
i 	 E 	 J 	 Pi(1=+) 	 T1/2
	 i_final 	 Br
 ---------------------- 
0:	 0   0+ -1.1e+15 fs
1:	 0.56293   2+ 18200 fs
   0 : 1
2:	 1.10844   2+ 8000 fs
   1 : 0.5956
   0 : 0.4044
3:	 1.41008   4+ 1800 fs
   1 : 1
4:	 1.53946   3+ 1800 fs
   2 : 0.6672
   1 : 0.3328
5:	 1.91107   0+ 800 fs
   1 : 1
6:	 2.01987   4+ 1800 fs
   2 : 1
7:	 2.2049   2+ 10 fs
   2 : 0.6672
   0 : 0.3328
```

It's not a bug in a way. When you don't provide the halflive, the code will not know whether the state should decay or not. So the branching ratio is `nan`

**Comment by fzeiser** [comment]
See here for a possible modification of the level scheme. This would correspond to stating that we should observe these gammas in all cases. This may or maynot be correct.
[mylevels_z032.dat.zip](https://github.com/fzeiser/RAINIER/files/4730883/mylevels_z032.dat.zip)

You have to check yourself whether I've also changed other levels then 7 and 9, no guarantees ;P.

**Comment by aspyrou** [comment]
Thanks Fabio. That seems to fix this error
