### ISSUE TITLE
Question about ExSelect vs ExSingle (err: No level to populate for Ex=6)

### ISSUE THREAD

**Issue by hannahberg** [fzeiser/RAINIER#21]
Hello again,

I am using the latest release of RAINIER and I am having some issues with using ExSelect. For Ni-71, I am trying to go from 6 MeV from 5/2-, 7/2- and 9/2-. This works fine with each one separately with ExSingle, but when I try to do so with ExSelect I get this issue:
```
err: No level to populate for Ex=6
 check spin-parity of generated continuum level vs population from bExSelect

```

Is there anything I can do to get this to work? It doesn't seem to search for levels to populate as it does in ExSingle. Here is my settings and mylevels_028.dat where I run into the issue: [settings_mylevels.zip](https://github.com/fzeiser/RAINIER/files/5070673/settings_mylevels.zip)

**Comment by fzeiser** [comment]
Let's try to understand whether the error makes sense or not. Here is the level "scheme" I get from your file:
```
root [2] PrintConLvl()
****** Constructed ******
More levels exist at higher spins
Parity   - - - - - - - - - -  + + + + + + + + + + 
Spin Bin 9 8 7 6 5 4 3 2 1 0  0 1 2 3 4 5 6 7 8 9 
E(MeV)   
1.280    0|0|0|0|0|0|0|0|0|0| 0|0|0|0|0|0|0|0|0|0|
[...]
5.995    0|0|0|1|1|3|2|0|1|1| 0|1|1|1|2|2|2|0|0|0|
6.007    0|1|0|0|0|1|0|1|1|1| 0|1|0|0|1|2|1|0|0|0|
6.020    0|1|2|1|1|0|1|1|1|0| 0|1|2|2|1|0|1|0|1|0|
```

So one has to find out whether ExI = 6 will select the 5.995 or 6.007 bin. Then one can see whether the  5/2-, 7/2-, and 9/2- states are present.

**Comment by hannahberg** [comment]
So if it is not able to populate all three in the same initial state at 6.007 or 5.995 it will not work at all?

**Comment by fzeiser** [comment]
Check the level scheme for `bExSingle`, it'll look quite different:

 ```
root [2] PrintConLvl()
****** Constructed ******
More levels exist at higher spins
Parity   - - - - - - - - - -  + + + + + + + + + + 
Spin Bin 9 8 7 6 5 4 3 2 1 0  0 1 2 3 4 5 6 7 8 9 
E(MeV)   
1.279    0|0|0|0|0|0|0|0|0|0| 0|0|0|0|0|0|0|0|0|0|
[...]
5.982    0|1|2|2|1|0|2|0|2|1| 0|1|1|1|1|3|1|1|0|1|
5.994    0|0|0|0|0|0|2|2|2|0| 0|2|0|0|2|0|0|0|1|0|
```

It stops at 6 MeV, and the binning is slightly different. Thus you might a) have drawn slightly other random number, thus that there are levels or b) one has to find out what level `bExSingle` populates if there is no say 1/2- level in the highest created energy bin (Ex=6 MeV). It might be default go to the bin at Ex - 1 binwidth; if no level is found repeating down.

**Comment by fzeiser** [comment]
> So if it is not able to populate all three in the same initial state at 6.007 or 5.995 it will not work at all?

No, it's a warning, given as a `cout` starting with `err`. It's not a error as is `sys.error`

**Comment by hannahberg** [comment]
So it will still work with the error or should I try to get it to search for lower levels if it doesn't find anything next to the initial bin?

**Comment by fzeiser** [comment]
It depend what you mean with "works" really. Check the histograms mentioned above to see whether that's what you want. Otherwise it might be easier if you just want to populate something in the region of 6 MeV, not specific levels at some bin, to either find with `PrintConLvl` where the states exists - or you populate with the `bExFullRxn` option, which has the "search nearest" included,

**Comment by fzeiser** [comment]
My assumption is that `bExSingle` doesn't perform a check whether the level exists; it just assumes that you're there and then continues to calculate the width from there ...

**Comment by hannahberg** [comment]
Thank you, I'll have to look into which option will work best for the purpose I am using it for. The `h2ExI0PopLvl_0` seems to not show many levels below 6 MeV for `bExSelect`

**Comment by fzeiser** [comment]
Btw: you can isolate the problem using just a single level in `ExSelect`:
```
#ifdef bExSelect // similar to Beta decay
const double g_adExI[] = {6}; // MeV
const double g_adSpI[]  = {4.5}; // hbar
const double g_anParI[] = {0}; // Pi
const double g_adBRI[]   = {1.}; // Branching Ratio: has to sum up to 1.0
#endif
```
where you will see that the missing 5/2- is the problem

**Comment by fzeiser** [comment]
> The h2ExI0PopLvl_0 seems to not show many levels below 6 MeV for bExSelect

What do you mean / what is your point there?

**Comment by hannahberg** [comment]
> > The h2ExI0PopLvl_0 seems to not show many levels below 6 MeV for bExSelect
> 
> What do you mean / what is your point there?

If that would affect the 5/2 state, but it will only show the populated states. I might have misunderstood what it shows versus the `PrintConLvl()` to see what state it chooses in the start.

**Comment by fzeiser** [comment]
- `PrintConLvl`: states generates, levels "existing" in the nucleus
- `h2ExI0PopI_0`: levels (directly) populated; in your case it must be [5, 7, 9]/2- at Ex ≃ 6 MeV
- `h2ExI0PopLvl_0`: population including decays, so also levels at Ex < 6 MeV until you reach the gs.

**Comment by fzeiser** [comment]
Did this help? I still don't understand what you last question/comment is about

**Comment by hannahberg** [comment]
> Did this help? I still don't understand what you last question/comment is about

Yes, it did. I was just wondering if it could not combine different initial states for each spin to populate if it wasn't available for 5/2 where 7/2 and 9/2 had states available.

**Comment by fzeiser** [comment]
Maybe it helps for your understanding to run the `ExSelect` option, but with one level at the time and see the effect. then you combine them.

PS: I guess you know, but you can choose different Ex_initials for ExSelect; like { 5.6, 6, 6 } or whatever you want

**Comment by fzeiser** [comment]
Note that it throws an warning ("err") message, but the depopulation may continue. You will only find out about this if you check the terminal, the spectra might just look fine. But are in a way non sense, because there was no level.
