### ISSUE TITLE
error: use of overloaded operator '+' is ambiguous on Mac OS Bur Sur

### ISSUE THREAD

**Issue by fzeiser** [fzeiser/RAINIER#25]
@dennismuecher reports following problem and solution when running RAINIER on Mac OS Bur Sur:

Running the sample file he receives following error:
```
4 warnings generated.
In file included from RAINIER_copy_C_ACLiC_dict dictionary payload:8:
././RAINIER_copy.C:99:49: error: use of overloaded operator '+' is ambiguous (with operand types
      'std::__1::basic_string<char>' and 'TString')
  ...szFile = g_sRAINIERPath + "/levels/z" + TString::Format("%03d",g_nZ) + "...
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is solved by declaring `g_sRAINIERPath` as a `TString`, not a `string`. I will push the fix.

**Comment by dennismuecher** [comment]
Hey Fabio

Der fix war am Ende nicht string durch TString zu ersetzen weil man dann Problem emit c_str() bekommt. Stattdessen habe ich dies hier gemacht:

TString szFile = g_sRAINIERPath + "/levels/z" + TString::Format("%03d",g_nZ) + ".dat";

Ersetzt durch

TString szFile = TString(g_sRAINIERPath) + "/levels/z" + TString::Format("%03d",g_nZ) + ".dat";

Dann laeuft alles

Danke!
Dennis

**Comment by fzeiser** [comment]
Thanks Dennis! -- On my machine  9129dba worked as well, so I didn't see the difference. Will commit the changes.
